### ISSUE TITLE
clean build directory before testing

### ISSUE THREAD

**Issue by nickhand** [rainwoodman/runtests#12]
otherwise newly-deleted files will still exist in the build install

**Comment by rainwoodman** [comment]
Yes. I was thinking about this.

- We shall not clean the build directory; the build is usually incremental -- only changed source code (for binary extensions) are rebuilt. This is one of the important features of the old runtests.py -- in projects like scipy it takes forever to do a full rebuild.

- We shall clean the install destination; this way if build/temp and build/lib are purged (either manually or via setup.py) then the tests run cleanly.

**Comment by rainwoodman** [comment]
This feature appears to have been added.
