### ISSUE TITLE
The standard script fails to run when PYTHONPATH is set.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/runtests#16]
Python prepends PYTHONPATH to sys.path. The pop one trick thus will only remove one object from the path rather than the current path, causing the import to fail.

We really need a different name for the default `runtests` script. What about `run-tests.py`? @nickhand

**Comment by nickhand** [comment]
``run-tests.py`` works for me

**Comment by rainwoodman** [comment]
Rename is done and release tagged. Time to rename the downstream packages.
