### ISSUE TITLE
collective errors hang

### ISSUE THREAD

**Issue by nickhand** [rainwoodman/runtests#9]
It seems that the '-x' option will work when the error is raised only on one rank, but not if all ranks run in to the same problem, at least on my mac...

**Comment by rainwoodman** [comment]
I think it boils down to one of the barriers. You can run with --mpirun="mpirun -n 4 xterm -e gdb -args" to launch a bunch of debuggers, and inspect the stacktrace -- I am not sure if the gdb on Mac supports python debugging. Mine does. Can you commit a test case that hangs?

**Comment by nickhand** [comment]
yeah I agree...just added a test case

**Comment by nickhand** [comment]
What was the motivation for adding the '-x' flag? Removing that flag seems to fix this issue

**Comment by rainwoodman** [comment]
Because of #8 . If you have multiple tests then the following tests will mismatch the barriers and other collective operations, and leading to other strange hangs. You don't observe this when there is only one test case in a test.

**Comment by rainwoodman** [comment]
I pushed a fix, and added '--single' to replace the quirky nargs='?' mpirun.

**Comment by nickhand** [comment]
great, was just pushing the same fix

**Comment by nickhand** [comment]
closed via c88a329
